Dockerize frontend
delta/DWoC-23-frontend pull request #2
Opened 2023-09-13 10:26 UTC by avyjit

2023-09-13 12:10 UTC, ZaBarudo requested changes

2023-09-13 12:10 UTC, ZaBarudo commented on Dockerfile
> +CMD ["yarn", "vite", "preview", "--host", "--port", "3000", "--no-open"]
`yarn preview` is for Dev purposes only. For Prod, use `yarn build`. Use a Multi-Stage Docker Build and serve it with nginx. Refer to [Festember 22](https://github.com/delta/Festember-frontend-2022).

2023-09-13 13:06 UTC, avyjit commented on Dockerfile
> +CMD ["yarn", "vite", "preview", "--host", "--port", "3000", "--no-open"]
Did the required changes.

2023-09-13 13:16 UTC, ZaBarudo approved these changes

2023-09-13 13:18 UTC, ZaBarudo requested changes
Use Docker Compose. Make a `.env` file (and a `.env.example`) and get the Host Port number from there.

2023-09-14 17:18 UTC, ZaBarudo approved these changes

2023-09-14 17:18 UTC, merged